name: CI

on: [push, pull_request]

jobs:
  build:
    name: My Job
    runs-on: ubuntu-18.04
    steps:
      - name: apt update
        run: sudo apt-get update
      - name: Install base packages
        run: |
          sudo apt-get install --yes \
          gpg \
          make \
          net-tools \
          software-properties-common
      - name: Add OPC UA ppa
        run: sudo add-apt-repository ppa:open62541-team/ppa && sudo apt-get update
      - name: Install Perl Modules for Testng and libopen62541
        run: |
          sudo apt-get install --yes \
          libdevel-checklib-perl \
          libopen62541-1 \
          libopen62541-1-dev \
          libopen62541-1-tools \
          libtest-exception-perl \
          libtest-leaktrace-perl \
          libtest-nowarnings-perl \
          libtest-pod-perl \
          libtest-requires-perl \
          libtest-tcp-perl \
          libtest-warn-perl
      - name: Checkout
        run: git clone https://github.com/ArnieSan/p5-opcua-open62541.git 
      - name: perl Makefile
        run: cd p5-opcua-open62541 && perl Makefile.PL
      - name: Make
        run: cd p5-opcua-open62541 && make
      - name: Test
        run: cd p5-opcua-open62541 && make test
