name: CI

on: [push, pull_request]

jobs:
  build:
    env:
      GITHUB_WORKSPACE: /home/runner/
    name: My Job
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Whereami
      run: pwd && echo XXX1 && ls -lad /home && echo XXX2 && ls -lad && echo XXX3 && ls -laR /github && echo XXX4 && ls -lad /home/runner
      #    - name: apt update
      #      run: sudo apt-get update
      #    - name: Install base packages
      #      run: |
      #        sudo apt-get install --yes \
      #        gpg \
      #        make \
      #        net-tools \
      #        software-properties-common
      #    - name: Add OPC UA ppa
      #      run: sudo add-apt-repository ppa:open62541-team/ppa && sudo apt-get update
      #    - name: Install Perl Modules for Testng and libopen62541
      #      run: |
      #        sudo apt-get install --yes \
      #        libdevel-checklib-perl \
      #        libopen62541-1 \
      #        libopen62541-1-dev \
      #        libopen62541-1-tools \
      #        libtest-exception-perl \
      #        libtest-leaktrace-perl \
      #        libtest-nowarnings-perl \
      #        libtest-pod-perl \
      #        libtest-requires-perl \
      #        libtest-tcp-perl \
      #        libtest-warn-perl
      #    - name: perl Makefile
      #      run: perl Makefile.PL
      #    - name: Make
      #      run: make
      #    - name: Test
      #      run: timeout 60 make test
