name: CI

on: [push, pull_request]

jobs:
  build:
    name: My Job
    runs-on: ubuntu-18.04
    steps:
      - name: apt update
        run: apt-get update
      - name: Install base packages
        run: |
          apt-get install --yes \
          gpg \
          make \
          net-tools \
          software-properties-common
